// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBAk5VVsj5h646OX_RPZhd3vLkLZhSFwc',
    appId: '1:804539744779:web:9c37ce09fa2c2db2ed7d0e',
    messagingSenderId: '804539744779',
    projectId: 'bisupply-14108',
    authDomain: 'bisupply-14108.firebaseapp.com',
    storageBucket: 'bisupply-14108.firebasestorage.app',
    measurementId: 'G-YCJHR5DNCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJxP_r038n_Vk1JwLu-230QKg8Cqf3pAo',
    appId: '1:804539744779:android:67f094d5ee50f48eed7d0e',
    messagingSenderId: '804539744779',
    projectId: 'bisupply-14108',
    storageBucket: 'bisupply-14108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9Qkbfq4MgRv2s-dFerjKp2C3d-wTnIs',
    appId: '1:804539744779:ios:9d262bdd5d8a682ced7d0e',
    messagingSenderId: '804539744779',
    projectId: 'bisupply-14108',
    storageBucket: 'bisupply-14108.firebasestorage.app',
    iosBundleId: 'com.example.mukadamBi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO9Qkbfq4MgRv2s-dFerjKp2C3d-wTnIs',
    appId: '1:804539744779:ios:9d262bdd5d8a682ced7d0e',
    messagingSenderId: '804539744779',
    projectId: 'bisupply-14108',
    storageBucket: 'bisupply-14108.firebasestorage.app',
    iosBundleId: 'com.example.mukadamBi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBAk5VVsj5h646OX_RPZhd3vLkLZhSFwc',
    appId: '1:804539744779:web:0b135deb24fc452eed7d0e',
    messagingSenderId: '804539744779',
    projectId: 'bisupply-14108',
    authDomain: 'bisupply-14108.firebaseapp.com',
    storageBucket: 'bisupply-14108.firebasestorage.app',
    measurementId: 'G-231K794RHL',
  );

}